### ISSUE TITLE
Urban dictionary commands sometimes fail with indexoutofbounds

### ISSUE THREAD

**Issue by DrEngi** [DrEngi/lmao-bot#117]
Fairly confident this is the issue, especially when there are no definitions found.

https://github.com/DrEngi/lmao-bot/blob/f318af6c20c44e083424cdb7249834c63ab91e59/lmao-bot/Modules/UtilityModule.cs#L62

**Comment by DrEngi** [comment]
Additionally, it seems some errors occur when creating a Urban embed: 

```
Discord.Commands.CommandException: Error occurred executing "urban" for RNT-zenzen#2767 in Hi We Are Bald/the-homo-housefuck.
 ---> System.ArgumentException: Field value must not be null or empty. (Parameter 'Value')
   at Discord.EmbedFieldBuilder.set_Value(Object value)
   at lmao_bot.Modules.UtilityModule.Urban(String word)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---```
