### ISSUE TITLE
lmao seenfromabove command failure

### ISSUE THREAD

**Issue by DrEngi** [DrEngi/lmao-bot#96]
`lmao seenfromabove` fails silently during to a missing resource issue, almost definitely a font it can't find. Make sure the reference to it has been updated.

```python
Ignoring exception in command seenfromabove:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
ret = await coro(*args, **kwargs)
File "/home/container/src/modules/fun.py", line 354, in cmd_seen_from_above
await seen_from_above(seen_from_above_person)
File "/home/container/src/modules/fun.py", line 172, in seen_from_above
fnt = ImageFont.truetype('fonts/arial.ttf', 32)
File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFont.py", line 280, in truetype
return FreeTypeFont(font, size, index, encoding, layout_engine)
File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFont.py", line 145, in __init__
layout_engine=layout_engine)
OSError: cannot open resource
```

**Comment by TheRockettek** [comment]
you are most probrably not running the script from the directory
